<div><span class="toggleNav">☰ </span><span>Filtrar búsqueda</span></div>
<div class="libros" id="libros">
</div>
<div class="paginacion" id="paginacion">
</div>
<div id="info" class="informacion">
	<div id="informacionImg">
		<div id="imgPortada"></div>
		<div><input type="button" id="reservar" value="Reservar"/></div>
	</div>
	<div id="informacionRes">RESUMEN</div>
	<div id="informacionFicha">
		<div id="ficha"></div>
		<span id="volver">
			Volver a la lista de libros
		</span>
	</div>
	
</div>
