 <div id= "inicio">
 <section class="wrapper2">
	  <div> </div>
     
    </section>
      <section class="posts">
  
	  <div class="post">
		
		<div class="contenido_post">
			<div class="post_txt">
				<h3>ULTIMAS PUBLICACIONES</h3>
				<p>
					
					
				</p>
			</div>
		</div>
	  </div>
	  
	  <div class="post">
		
		<div class="contenido_post">
			<div class="post_txt">
				<h3>AUTOR DEL MES</h3>
				<p>

				</p>
			</div>

		</div>
	  </div>
	  
	  <div class="post">
		
		<div class="contenido_post">
			<div class="post_txt">
				<h3>LIBROS DE LA SEMANA</h3>
				<p>

				</p>
			</div>

		</div>
	  </div>
	  <div class="post">
		
		<div class="contenido_post">
			<div class="post_txt">
				<h3>LIBROS RECOMENDADOS</h3>
				<p>

				</p>
			</div>

		</div>
	  </div> 
    </section>
</div>
