<div id="busqueda" class="oculto">
		<div id="cerrar_busqueda"><i class="fas fa-window-close"></i> Cerrar búsqueda</div>
		<div class="libros" id="libros_busqueda"></div>
		
	</div>
<div id="info" class="informacion">
	<div id="estadoLibro"></div>
	<div id="informacionImg">
		<div id="imgPortada"></div>
		<div><input type="button" id="reservar" value="Reservar"/></div>
	</div>
	<div id="informacionRes">RESUMEN</div>
	<div id="informacionFicha">
		<div id="ficha"></div>
		<span id="volver">
			Volver a la lista de libros
		</span>
		<span id="volverB">
			Volver a la lista de la búsqueda
		</span>
		<span id="volverI">
			Volver al inicio
		</span>
	</div>
	
</div>