<div id="formuDevolver">
<form id=devolverLibro">
	<div>
		<label>DNI Usuario:</label>
		<input type=text id="dni_usu">
		<spam id="error_dni"></spam>
	</div>
	<div>
		<label>Código Libro:</label>
		<input type=text id="cod_lib">
		<spam id="error_codigo"></spam>
	</div>
	<input type="button" id="devolverLibro" value="Devolver">
	<input type="button" id="pedirLibro" value="Prestar">
</form>
</div>