
	
    <section class="wrapper2">
	 
      <div id="myCarousel" class="carousel slide" data-ride="carousel">
					  <!-- Indicators -->
					  <ol class="carousel-indicators">
						<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
						<li data-target="#myCarousel" data-slide-to="1"></li>
						<li data-target="#myCarousel" data-slide-to="2"></li>
					  </ol>

					  <!-- Wrapper for slides -->
					  <div class="carousel-inner">
						<div class="item active">
						  <img src="img/carrusel1.jpg" alt="img">
						</div>

						<div class="item">
						  <img src="img/carrusel2.jpg" alt="img">
						</div>

						<div class="item">
						  <img src="img/carrusel3.jpg" alt="img">
						</div>
					  </div>

					  <!-- Left and right controls -->
					  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
						<span class="glyphicon glyphicon-chevron-left"></span>
						<span class="sr-only">Previous</span>
					  </a>
					  <a class="right carousel-control" href="#myCarousel" data-slide="next">
						<span class="glyphicon glyphicon-chevron-right"></span>
						<span class="sr-only">Next</span>
					  </a>
					</div>
    </section>
      <section class="posts">
  
	  <div class="post">
		
		<div class="contenido_post">
			<div class="post_txt">
				<h3>DIA DEL LIBRO</h3>
				<p>
					El Día Internacional del Libro es una conmemoración celebrada a nivel mundial con el objetivo de fomentar la lectura,
					la industria editorial y la protección de la propiedad intelectual por medio del derecho de autor. 
					Desde 1988 es una celebración internacional promovida por la UNESCO,
					el 15 de junio de 1989 se inició en varios países y en 2010 la celebración ya había alcanzado más de cien.
					<br>
					Fue natural que la Conferencia General de la UNESCO, celebrada en París en 1995, 
					decidiera rendir un homenaje universal a los libros y autores en esta fecha, alentando a todos, 
					y en particular a los jóvenes,a descubrir el placer de la lectura y a valorar las irreemplazables contribuciones de aquellos ,
					quienes han impulsado el progreso social y cultural de la humanidad. 			
					
				</p>
			</div>
			<div class="post_img">
				<img src="img/libro.jpg" alt="libro">
			</div>
		</div>
	  </div>
	  
	  <div class="post">
		
		<div class="contenido_post">
			<div class="post_txt">
				<h3>LECTURA DE LA OBRA LITERARI LA CELESTINA</h3>
				<p>
					La Celestina es el nombre con el que se ha popularizado la Tragicomedia de Calisto y Melibea,
					atribuida a Fernando de Rojas. 
					Su composición se remonta a los últimos años del siglo XV,
					durante el reinado de los Reyes Católicos en España y su extraordinario éxito editorial comenzó en el siglo XVI y continuó, 
					con altibajos, hasta su prohibición en 1792. 
					Hoy se hara una lectura de dicho libro.
				</p>
			</div>
			<div class="post_img">
				<img src="img/celestina.jpg" alt="celestina">
			</div>
		</div>
	  </div>
	  
	  <div class="post">
		
		<div class="contenido_post">
			<div class="post_txt">
				<h3>RECITAL DE POESIA</h3>
				<p>
					Traer vuestras poesias el dia 18 de abril ,
					realizaremos un recital , atreveros ,sez creativos , seguro que teneis mucho que decir es vuestro momento.
					Estaremos encantados de escuchar vuestras creaciones.
				</p>
			</div>
			<div class="post_img">
				<img src="img/poesia.jpg" alt="poesia">
			</div>
		</div>
	  </div>
	  
    </section>
	<section class="bloque2">
		<div>
			<header>CONÓCENOS</header><br>
			<p>
				Dirección: km 6,200, Av. de Andalucía, 28041 Madrid<br>
				Teléfono: 913 17 19 72<br>
				Provincia: Comunidad de Madrid<br>
			</p>
		</div>
	
	<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3039.7577437489813!2d-3.6974207856387!3d40.36989567937058!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd4226cdfefd6c59%3A0x5c599da87d0d06ff!2sIES%20Enrique%20Tierno%20Galv%C3%A1n!5e0!3m2!1ses!2ses!4v1585781197858!5m2!1ses!2ses" width="400" height="300"  style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0">
	</iframe>
	</section>
      