<footer>
<span>Quien tiene un libro, tiene un tesoro </span>
<nav class="redes">
	<ul>
		<li class="redes_sociales">
			<ul>
				<li>Twitter</li>
				<li>
					<a href="http://twitter.com"><i class="fab fa-twitter"></i></a>
				</li>
			</ul>
			<ul>
				<li>Facebook</li>
				<li>
					<a href="http://facebook.com"><i class="fab fa-facebook"></i></a>
				</li>
			</ul>
	</ul>
</nav>
</footer>
</div>
